KNN support for spoints
postgrespro/pgsphere pull request #116
Opened 2023-12-12 05:00 UTC by vitcpp

This is the original patch for review and improvement.

2023-12-12 06:49 UTC, esabol requested changes

2023-12-12 06:49 UTC, esabol commented on doc/indices.sgm
> +          GiST index can be used also for fast finding points closest to the given one
Change "fast finding points" to "quickly finding the points".

2023-12-12 06:49 UTC, esabol commented on doc/indices.sgm
> +          is used, as shown in an example below.
Remove "is used" and move the comma to be at the end of "operator" on the previous line.

2023-12-12 06:49 UTC, esabol commented on doc/indices.sgm
> -
Based on the other `</sect1>` tags I saw, I don't this blank line before `</sect1>` should have been removed.

2023-12-12 06:49 UTC, esabol commented on pgs_gist.sql.in
> +CREATE FUNCTION g_spoint_distance(internal, spoint, smallint, oid, internal)
Create an upgrade script and add this function to it.

2023-12-12 06:49 UTC, esabol commented on pgs_gist.sql.in
> +   OPERATOR	 17	<-> (spoint, spoint) FOR ORDER BY float_ops,
Whitespace doesn't match the other `OPERATOR` lines surrounding this addition. The `17` should line up with the `16` on the previous line for starters.

2023-12-12 06:49 UTC, esabol commented on src/gist.c
> +static double distance_vector_point_3d (Vector3D* v, double x, double y, double z) {
Change `Vector3D* v` to `Vector3D *v` in order to match the coding style of pgsphere.

2023-12-12 06:49 UTC, esabol commented on src/gist.c
> +	return acos ( (v->x * x + v->y * y + v->z * z) / sqrt( x*x + y*y + z*z ) ); //  as v has length=1 by design
Remove the space after `acos`.

2023-12-12 06:49 UTC, esabol commented on src/gist.c
> +			if(v_point.x < v_low.x) {
Change `if(` to `if (` throughout this function in order to match the coding style of pgsphere.

2023-12-12 06:49 UTC, esabol commented on src/gist.c
> +						retval = distance_vector_point_3d (&v_point, v_low.x, v_low.y, v_low.z); //point2point distance
Change `distance_vector_point_3d (` to `distance_vector_point_3d(` throughout this function in order to match the coding style of pgsphere.

2023-12-12 06:49 UTC, esabol commented on src/gist.c
> +
An extra blank line doesn't need to be added here.

2023-12-12 06:49 UTC, esabol commented on src/gist.c
> +
Two too many blank lines added here, I think.

2023-12-12 15:02 UTC, vitcpp commented
I used pgindent to reformat new functions in gist.c.

2023-12-12 15:48 UTC, esabol requested changes
A couple more very minor changes to the documentation, please.

Still needs an upgrade script. And maybe a version bump?

2023-12-12 15:48 UTC, esabol commented on doc/indices.sgm
> +          GiST index can be also used for quickly finding the points closest to the given one
Change `GiST index` to `A GiST index`. Sorry should have caught that in my previous review.

2023-12-12 15:48 UTC, esabol commented on doc/indices.sgm
> +           To find points closest to a given spherical position, use the <literal>&lt;-&gt;</literal> operator:
Change `To find points` to `To find the points`.

2023-12-17 17:34 UTC, esabol requested changes

2023-12-17 17:34 UTC, esabol commented on upgrade_scripts/pg_sphere--1.4.2--1.5.0.sql.in
> +CREATE FUNCTION g_spoint_distance(internal, spoint, smallint, oid, internal)
Use `CREATE OR REPLACE` in the upgrade script? See issue #111.

2023-12-19 16:20 UTC, esabol approved these changes
Looks good to me!

2023-12-20 12:00 UTC, vitcpp commented
Squashed latest 3 commits. The two commits are kept - the original commit and the commit with code adjustment.

2023-12-22 08:13 UTC, merged