Added calculation of the distance between a line and a point
postgrespro/pgsphere pull request #40
Opened 2023-08-02 10:15 UTC by Darya177777

2023-08-02 17:29 UTC, esabol commented
CI tests failed. Make sure your fork is sync'ed with this repo. You might need to just update the line numbers in some expected output files?

2023-08-04 04:31 UTC, Darya177777 commented
@esabol : All tests fixed. Please, re-review.

2023-08-04 07:42 UTC, esabol requested changes
Thank you for this! Looks pretty good to me. Just some minor changes, I think.

2023-08-04 07:42 UTC, esabol commented on doc/operators.sgm
> +                between points, circles, between point and circle, and between point and line. If the
Does this line exceed 79 characters? If so, please word-wrap.

2023-08-04 07:42 UTC, esabol commented on pgs_line.sql.in
> +  'distance between spherical line and spherical point';
All the other COMMENT ON FUNCTIONs in this file start with "returns..." I know that seems redundant, but I think it's best to fit in with the convention of the other COMMENTs.

2023-08-04 07:42 UTC, esabol commented on expected/line.out
> +SELECT round( CAST(sline '( 90d, 0d, 0d, XYZ ), 40d ' <-> spoint '( 0d, 90d )' as numeric), 14);
What about the distance between a point and a line? I.e., the commutative property. Is that implemented? If not, it should be. If it is, then it should be tested.
```
SELECT round( CAST(spoint '( 0d, 90d )' <-> sline '( 90d, 0d, 0d, XYZ ), 40d ' as numeric), 14);
```

2023-08-04 09:55 UTC, Darya177777 commented
All fixed.

2023-08-04 19:29 UTC, esabol commented
> All fixed.

OK, looking better! @vitcpp will probably have some comments as well.

2023-08-04 20:53 UTC, vitcpp commented
@Darya177777 Could you also please rebase on the newest version and update the upgrade script upgrade_scripts/pg_sphere--1.2.3--1.3.0.sql.in. Such script is used when updating the extension to a newer version using ALTER EXTENSION UPDATE TO command. Once you have introduced a new function the upgrade script should be updated.

2023-08-05 07:45 UTC, vitcpp requested changes

2023-08-05 07:45 UTC, vitcpp commented on src/line.c
> +	if (FPle(spoint_dist(p, &fp), spoint_dist(p, &sp)))
I would propose to this code faster like this:
fpdist = spoint_dist(p, &fp);
spdist = spoint_dist(p, &sp);
return Min(fpdist, spdist);

2023-08-05 07:45 UTC, vitcpp commented on src/line.c
> +	SLine	   *s = (SLine *) PG_GETARG_POINTER(0);
I would propose to add const prefix in local variable declarations.

2023-08-05 07:45 UTC, vitcpp commented on src/line.c
> +	SPoint	   *p = (SPoint *) PG_GETARG_POINTER(0);
I would propose to add const prefix in local variable declarations.

2023-08-05 07:45 UTC, vitcpp commented on expected/line.out
> +SELECT round( CAST(sline '( 90d, 0d, 0d, XYZ ), 40d ' <-> spoint '( 0d, 90d )' as numeric), 14)   =
I think round(CAST... is not necessary.
I would propose to add SET extra_float_digits TO -3; in the beginning of file. It reduces the number of output digits.

I've attached the modified line.sql 
[line.sql.zip](https://github.com/postgrespro/pgsphere/files/12266486/line.sql.zip)

2023-08-08 08:55 UTC, vitcpp commented
@Darya177777 Could you please squash two commits into one.

2023-08-08 09:00 UTC, vitcpp commented on doc/index.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">
This file is generated. It should not be added in the commit. Could you please remove it?

2023-08-08 09:00 UTC, vitcpp commented on doc/types.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">
This file should be removed from the commit.

2023-08-08 09:00 UTC, vitcpp commented on doc/x20.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">
Remove this file from the commit.

2023-08-08 09:01 UTC, vitcpp commented on doc/x46.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd">
Remove this file from the commit.

2023-08-08 09:02 UTC, vitcpp commented on expected/init_test.out
> +SET client_min_messages TO NOTICE;
Remove this file from the commit.

2023-08-08 09:02 UTC, vitcpp commented on log/initdb.log
> +Running in no-clean mode.  Mistakes will not be cleaned up.
Remove this file from the commit.

2023-08-08 09:02 UTC, vitcpp commented on log/postmaster.log
> +2023-08-08 15:16:01.222 +07 postmaster[14615] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
Remove this file from the commit.

2023-08-08 09:02 UTC, vitcpp commented on logfile
> +2023-08-08 14:58:03.794 +07 [12364] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
Remove this file from the commit.

2023-08-09 07:36 UTC, vitcpp commented
PR seems to be ok. I need to do some testing before merge.

2023-08-09 19:20 UTC, esabol commented
> @Darya177777 Could you please squash two commits into one.

@vitcpp, doesn't GitHub automatically squash commits on merge these days? I've been under the impression that it does, but maybe I'm used to GitLab.

2023-08-10 06:35 UTC, vitcpp commented
@esabol I'm not sure about github feature to squash commits. I will check it. I'm concerned which final comment will appear in commit after squashing. I'm not sure that simple joining of commit messages is a good idea. Furthermore, it is harder to review multiple commits where latest commit overwrites some changes of the previous commit. PR should contain the final version of the changes. It can contain multiple commits but these commits should be used to logically separate the changes. They should not touch the same code.

2023-08-10 10:09 UTC, vitcpp approved these changes

2023-08-10 10:27 UTC, vitcpp commented
@Darya177777 Could you please fix the tests? Thank you.

2023-08-10 14:35 UTC, vitcpp requested changes

2023-08-10 14:35 UTC, vitcpp commented on src/sscan.c
> -#line 2 "sscan.c"
This file is generated. It should be removed from the commit.

2023-08-10 14:42 UTC, vitcpp commented
@Darya177777 You have added sscan.c file to the commit. It shouldn't be added. Could you please remove it from the commit.

2023-08-10 15:57 UTC, esabol commented
> @esabol I'm not sure about github feature to squash commits. I will check it. I'm concerned which final comment will appear in commit after squashing. I'm not sure that simple joining of commit messages is a good idea. Furthermore, it is harder to review multiple commits where latest commit overwrites some changes of the previous commit. PR should contain the final version of the changes. It can contain multiple commits but these commits should be used to logically separate the changes. They should not touch the same code.

@vitcpp, you can edit the merge commit message to whatever you want when squashing and merging, according to this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

2023-08-10 19:20 UTC, vitcpp commented
> @vitcpp, you can edit the merge commit message to whatever you want when squashing and merging, according to this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

@esabol  Thank you very much! I will take a look.

2023-08-11 05:50 UTC, vitcpp approved these changes

2023-08-11 06:03 UTC, vitcpp requested changes
@Darya177777 It seems we missed to make some changes in pg_sphere--1.2.3--1.3.0.sql.in. This script is used to upgrate pgsphere versions in the existing database. Just copy the contents of pgs_line.sql.in into this file.

2023-08-11 08:17 UTC, Darya177777 commented
@vitcpp I have made some changes in pg_sphere--1.2.3--1.3.0.sql.in. Please, re-review.

2023-08-11 09:44 UTC, esabol approved these changes
Looks good to me.

2023-08-11 15:27 UTC, vitcpp approved these changes

2023-08-11 20:06 UTC, merged