Add "pgindent" rule for make to run pgindent
postgrespro/pgsphere pull request #71
Opened 2023-09-28 14:20 UTC by vitcpp

Implemented pgindent rule to run pgindent on the code. Utilities pgindent and pg_bsd_indent should be in the PATH or specified in the make command line: make PGINDENT=<...> PGBSDINDENT=<...> pgindent

2023-09-29 15:23 UTC, esabol approved these changes

2023-10-23 15:20 UTC, df7cb commented on pgindent-typedefs.list
> +CPoint
I'd suggest to sort the list - it looks like it is, except for that last value.

2023-11-01 20:33 UTC, esabol commented
Where do you get `pgbsdindent`? My `postgresql-15.4/src/tools/pgindent/` directory only compiles the `pgindent` and `pgperltidy` executables....

Hmmm, the `README` in `postgresql-15.4/src/tools/pgindent/` says to `git clone https://git.postgresql.org/git/pg_bsd_indent.git`. That compiles `pg_bsd_indent`, not `pgbsdindent`. I'm confused as to the difference. I presume they are compatible, but why is the name of the executable different?

Might be time to add a `CONTRIBUTING.md` file to the repo to explain this stuff?

2023-11-01 21:07 UTC, df7cb commented
pg_bsd_indent got imported into the postgresql git, but only in the current master branch. The idea is that different branches might have different indentation rules or something.

https://git.postgresql.org/gitweb/?p=postgresql.git;a=tree;f=src/tools/pg_bsd_indent

(`pg_bsd_indent` is the correct spelling, `pgbsdindent` doesn't exist. But `pgindent` exists, for added confusion...)

2023-11-01 21:13 UTC, df7cb commented
At the top of the pgindent/README file, there is a link to a blog post that explains how to use it on non-core code:

https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/tools/pgindent/README

http://adpgtech.blogspot.com/2015/05/running-pgindent-on-non-core-code-or.html

Dropping a link to at least the first one would make sense, perhaps as a comment on the Makefile pgindent rule.

2023-11-02 06:40 UTC, esabol commented
Oops, I'm not sure why I thought the executable is named "pgbsdindent". The PR description and the changes to the `Makefile` clearly show its "pg_bsd_indent". I guess I was just temporarily blind. Anyway, thanks for clarifying, @df7cb.

I guess I'd still like to see some text added to the `README.pg_sphere` file **or** comment(s) added to the `Makefile` **or** a `CONTRIBUTING.md` file added to the repo which explains where/how to get the `pgindent` and `pg_bsd_indent` executables.

2023-11-02 08:30 UTC, vitcpp commented
@esabol I think, we have to put some explanations to CONTRIBUTING.md but I propose to do it later. Now CONTRIBUTING.md is too old and not complete. It should be updated. What I propose to do right now is to put some information into the Makefile (above the rule). To run pgindent a postgresql source tree should be installed because it contains sources of pg_bsd_indent and pgindent, or these files should be somehow available in PATH by some other means. The pgindent, pg_bsd_indent binaries should be in the PATH. 

I agree with @df7cb to put the link into the Makefile:  
https://git.postgresql.org/gitweb/p=postgresql.git;a=blob;f=src/tools/pgindent/README

2023-11-02 08:44 UTC, df7cb commented
Fwiw I plan to change the PG17 Debian packages to include pg_bsd_indent and pgindent, if that helps.

https://wiki.postgresql.org/wiki/Apt/FAQ#Development_snapshots

2023-11-08 00:21 UTC, esabol requested changes

2023-11-08 00:21 UTC, esabol commented on Makefile
> +# To launch pgindent, set the PATH environment variable to the directories
I propose changing this line to the following:

To use pgindent, set the PATH environment variable to include the directories

2023-11-08 00:21 UTC, esabol commented on Makefile
> +# in the postgresql>/src/tools/pg_bsd_indent directory, where <postgresql>
There should be a less-than symbol before "postgresql" on this line, I believe.

2023-11-08 08:36 UTC, vitcpp commented
Rebased, fixed issues reported in the review

2023-11-08 16:36 UTC, esabol reviewed
Looks good!

2023-11-09 08:12 UTC, merged